# Generated by Django 5.2.9 on 2025-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_api', '0003_add_paper_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
