# Generated by Django 5.2.9 on 2025-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_api', '0004_add_paper_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='bibtex',
            field=models.TextField(blank=True, default=''),
        ),
    ]
