# Generated by Django 5.2.9 on 2026-01-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_api', '0007_restructure_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
