# Generated by Django 5.2.9 on 2026-01-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_api', '0008_message_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_index', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, default='', max_length=1000)),
                ('claimed_authors', models.CharField(blank=True, default='', max_length=500)),
                ('claimed_date', models.CharField(blank=True, default='', max_length=50)),
                ('openalex_metadata', models.JSONField(blank=True, null=True)),
                ('verified_metadata', models.JSONField(blank=True, null=True)),
                ('content_fetch', models.JSONField(blank=True, null=True)),
                ('content_verification', models.JSONField(blank=True, null=True)),
                ('credibility_score', models.FloatField(default=5.0)),
                ('credibility_notes', models.TextField(blank=True, default='')),
                ('overall_quality', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['paper_index'],
            },
        ),
        migrations.DeleteModel(
            name='PaperVerificationCache',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='hallucination_warnings',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='paper_verifications',
        ),
        migrations.AddField(
            model_name='paperverification',
            name='verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_verification_details', to='openai_api.verification'),
        ),
    ]
