# Generated by Django 5.2.9 on 2026-01-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_api', '0009_paperverification_delete_paperverificationcache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperverification',
            name='overall_assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paperverification',
            name='paper_quality',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperverification',
            name='summary_evaluation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
